### ISSUE TITLE
issue with 0.5 degrees jumps

### ISSUE THREAD

**Issue by Dannino-Shuli** [sargue/learn-broadlink#1]
HI,

thank you so much for this great great script!!!
I just have 1 issue - one of my ACs has 0.5 degrees jumps. how can I solve this??? I tried to put "0.5" in the "precision" but nothing helps....

pleaseeeee advise :)

**Comment by sargue** [comment]
Yep, you're right. The code is currently assuming natural numbers for the temperature. You will need to change the code on `learn.py` to handle 0.5 increments. Perhaps the proper way would be to read the precision from the json file.

I do not plan to implement that myself. I don't need it, and I just shared this code in case it was useful for someone. If you want to give it a try and manage to make it work I would happily accept a PR.

**Comment by Dannino-Shuli** [comment]
Dear Sergi,

Thank you very much for the prompt reply, sir.
Can you please elaborate regarding if I would want to give it a try? Is it
something to open the py script and just change the text or something
"deeper"? (sorry for the quotation, I'm not familiar with code AT ALL 😅)
BTW - I have a set of commands that I already did manually in the HA, as
learn.command script. It took me around 3 hours and it was only 20-28
degrees. I thought to take those codes and put them manually on the
"smartir" table but it is very hard work then I said, I'd prefer to run the
py script and do it once and for all. On the other hand, I thought maybe to
use Copilot\GPT to take those codes and arrange them for me in the form of
"smartir", even though I didn't record the entire states.

What do you think?

Another thing please - do you know maybe why the smartir appears as
"unavailable" in the Alexa app?

Thanks and regards!

**Comment by sargue** [comment]
> Can you please elaborate regarding if I would want to give it a try? Is it
something to open the py script and just change the text or something
"deeper"? (sorry for the quotation, I'm not familiar with code AT ALL 😅)

Well, in a nutshell, yes, it's about changing the python script. But if you have no coding knowledge at all it won't be an easy task. But it's nonetheless a perfect starting point to learn!

Using some LLM like ChatGPT to help you with that might work, but I guess you might need some basic understanding about what's happening.

No idea about Alexa, I've never used any of those assistants / smart speakers.

My suggestion would be to reach to the Home Assistant forum (https://community.home-assistant.io/). There's plenty of excellent people on there who might help or even have the solution.

**Comment by Dannino-Shuli** [comment]
Thank you very much sir, will do! :)

**Comment by eisack00** [comment]
```
    min_temperature = data['minTemperature']
    max_temperature = data['maxTemperature']
    temp_range = [round(x * 0.5, 1) for x in range(int(min_temperature * 2), int((max_temperature + 0.5) * 2))]
```
    
    It works with this minor amendment :> 
    
    Haven't tested it in HA yet, but it works for learning the IR commands. 
    Alternatively, you can simply double the min/max range and then halve the units in labeling after the fact.

**Comment by sargue** [comment]
Thanks @eisack00 for the patch and @PhompAng for the PR.

**Comment by Dannino-Shuli** [comment]
> ```
>     min_temperature = data['minTemperature']
>     max_temperature = data['maxTemperature']
>     temp_range = [round(x * 0.5, 1) for x in range(int(min_temperature * 2), int((max_temperature + 0.5) * 2))]
> ```
> 
> ```
> It works with this minor amendment :> 
> 
> Haven't tested it in HA yet, but it works for learning the IR commands. 
> Alternatively, you can simply double the min/max range and then halve the units in labeling after the fact. 
> ```

Hello!

Apologies! I missed this reply :(
where exactly do I find this these 3 lines, in the py code or should I put them on the json file?

Thank you so much!
